### ISSUE TITLE
你好，当vite.config.js不在根目录时，会报错误，看了下源码，似乎不支持html绝对路径？

### ISSUE THREAD

**Issue by laixiaotao** [windsonR/vite-plugin-virtual-html#13]
failed to load config from F:\Work Projects\vue-slm\vite\vite.config.js
error when starting dev server:
TypeError: process.cwd(...).replaceAll is not a function
    at Object.<anonymous> (F:\Work Projects\vue-slm\node_modules\vite-plugin-virtual-html\src\types.js:8:29)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (F:\Work Projects\vue-slm\node_modules\vite-plugin-virtual-html\src\plugin.js:26:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by windsonR** [comment]
我测试了下,不在根目录时,使用`--config`指定`vite.config.js`文件,和在根目录的`vite.config.js`行为完全相同,没有报错.

**Comment by windsonR** [comment]
你的这个报错是报的replaceAll,这个在新的版本里边我已经移除了.
